[package]
name = "collectives-westend-runtime-constants"
version = "1.0.0"
authors.workspace = true
edition.workspace = true
license = "Apache-2.0"
description = "Westend Collectives Parachain Runtime Constants"